
name: Publish Docker image

on:
  push:
    branches: ['main'] #ketika branch main ke trigger

jobs:
  push_to_registry: #menjalankan push to registry
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest #default virtual machine
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3 #command default untuk clone repository github ke VM

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker #tags dan label akan diinput muncul di docker images kolom Tags
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: minangkaracr/bflp-ci-cd

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
